#+title: Exercise 1

** Exercise
**** Level 1

1) Get user input using prompt(“Enter your age:”). If user is 18 or older , give feedback:'You are old enough to drive' but if not 18 give another feedback stating to wait for the number of years he needs to turn 18.

   #+begin_src js
Enter your age: 30
You are old enough to drive.

Enter your age:15
You are left with 3 years to drive.
   #+end_src

   #+begin_src js :results output
let enteredAge = 30

if (enteredAge >= 18) {
    console.log('You are old enough to drive.')
}
else {
    let leftAge = 18 - enteredAge
    console.log(`You are left with ${leftAge} years to drive`)
}
   #+end_src

   #+RESULTS:
   : You are old enough to drive.

2) Compare the values of myAge and yourAge using if … else. Based on the comparison and log the result to console stating who is older (me or you). Use prompt(“Enter your age:”) to get the age as input.

   #+begin_src js
Enter your age: 30
You are 5 years older than me.
   #+end_src

   #+begin_src js :results output
const myAge = 28

let yourAge = 45

if (yourAge > myAge) {
    let difference = yourAge - myAge
    console.log(`You are ${difference} years older than me.`)
}
else if (yourAge === myAge) {
    console.log('You are same age as me.')
}
else {
    let difference = myAge - yourAge
    console.log(`You are ${difference} year younger than me.`)
}
   #+end_src

   #+RESULTS:
   : You are 17 years older than me.

3) If a is greater than b return 'a is greater than b' else 'a is less than b'. Try to implement it in two ways

   #+NAME: variables-buttons
   #+begin_src js
let a = 4
let b = 3
   #+end_src

   - using if else

     #+begin_src js :results output :noweb yes
<<variables-buttons>>
if (a > b) {
    console.log(`${a} is greater than ${b}`)
}
else {
    console.log(`${b} is greater than ${a}`)
}

     #+end_src

     #+RESULTS:
     : 4 is greater than 3

   - using ternary operators

     #+begin_src js :results output :noweb yes
<<variables-buttons>>
a > b ? console.log(`${a} is greater than ${b}`) : console.log(`${b} is greater than ${a}`)
     #+end_src

     #+RESULTS:
     : 4 is greater than 3

4) Even numbers are divisible by 2 and the remainder is zero. How do you check, if a number is even or not using JavaScript?

   #+begin_src js
Enter a number: 2
2 is an even number

Enter a number: 9
9 is is an odd number.
   #+end_src

   #+begin_src js :results output
let num = 2
if (num % 2 === 0) {
    console.log(`${num} is an even number`)
}
else {
    console.log(`${num} is an odd number`)
}
   #+end_src

   #+RESULTS:
   : 2 is an even number

   #+begin_src js :results output
let num = 9
num % 2 === 0 ? console.log(`${num} is an even number`) : console.log(`${num} is an odd number`)
   #+end_src

   #+RESULTS:
   : 9 is an odd number
