#+title: Exercise 3

** Exercise
*** Level 3

1) The following is an array of 10 students ages: js =const ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]=  - Sort the array and find the min and max age - Find the median age(one middle item or two middle items divided by two) - Find the average age(all items divided by number of items) - Find the range of the ages(max minus min) - Compare the value of (min - average) and (max - average), use abs() method

   #+NAME: ages-array
   #+begin_src js
const ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
   #+end_src

   - Finding minimum or maximum age

     #+NAME: sorted-array
     #+begin_src js :results output :noweb yes
<<ages-array>>
let sorted = ages.sort((a, b) => a - b)
     #+end_src

     #+begin_src js :results output :noweb yes
<<sorted-array>>
console.log('Minimum Age : ' + sorted[0],'\n','Maximum Age : ' + sorted[sorted.length -1])
     #+end_src

     #+RESULTS:
     : Minimum Age : 19
     :  Maximum Age : 26

   - median age

     #+begin_src js :results output :noweb yes
<<sorted-array>>
if (sorted.length % 2 !== 0) {
   let index = Math.floor(sorted.length / 2)
    console.log(sorted[index])
}
else {
    let lowerNum = Math.floor(sorted.length / 2)
    console.log((sorted[lowerNum] + sorted[lowerNum + 1]) / 2)
}
     #+end_src

     #+RESULTS:
     : 24

   - Agerage age

     #+NAME: average-value
     #+begin_src js :results output :noweb yes
<<sorted-array>>
let total = 0;
for (let i in ages) {
    total = total + ages[i]
}
let average = total / ages.length
     #+end_src

     #+begin_src js :results output :noweb yes
<<sorted-array>>
console.log(average)
     #+end_src

     #+RESULTS: average-value
     : 22.8

   - Range of Age

    #+begin_src js :results output :noweb yes
<<sorted-array>>
let range = sorted[sorted.length - 1] - sorted[0]
console.log(range)
    #+end_src

    #+RESULTS:
    : 7

   - Compare Values
     - Minimum - Average
       #+begin_src js :results output :noweb yes
<<average-value>>
let value = Math.abs(sorted[0] - average)
console.log(value)
       #+end_src

       #+RESULTS:
       : 3.8000000000000007

     - Maximux - Average
       #+begin_src js :results output :noweb yes
<<average-value>>
let value = Math.abs(sorted[sorted.length - 1] - average)
console.log(value)
       #+end_src

       #+RESULTS:
       : 3.1999999999999993

2) Slice the first ten countries in the countries array.
   #+NAME: countries-array
   #+begin_src js :results output
const countries = [
    'Albania',
    'Bolivia',
    'Canada',
    'Denmark',
    'Ethiopia',
    'Finland',
    'Germany',
    'Hungary',
    'Ireland',
    'Japan',
    'Kenya'
]
   #+end_src

   #+begin_src js :results output :noweb yes
<<countries-array>>
console.log(countries.slice(0, 10))
   #+end_src

   #+RESULTS:
   : [
   :   'Albania',  'Bolivia',
   :   'Canada',   'Denmark',
   :   'Ethiopia', 'Finland',
   :   'Germany',  'Hungary',
   :   'Ireland',  'Japan'
   : ]

3) Find the middle countries in the countries array.
   #+begin_src js :results output :noweb yes
<<countries-array>>
let index = Math.floor(countries.length / 2)
if (countries.length % 2 === 0) {
    console.log(countries[index], countries[index + 1])
}
else {
    console.log(countries[index])
}

   #+end_src

   #+RESULTS:
   : Finland

4) Divide the countries array into two equal arrays if it is even. If country array is not even, one or more countries for the first half.
   #+begin_src js :results output :noweb yes
<<countries-array>>
let index = Math.floor(countries.length / 2)
if (countries.length % 2 === 0) {
    let firstHalf = countries.splice(0, index)
    console.log(firstHalf, countries)
}
else {
    let firstHalf = countries.splice(0, index + 2)
    console.log(firstHalf, countries)
}
   #+end_src

   #+RESULTS:
   : [
   :   'Albania',
   :   'Bolivia',
   :   'Canada',
   :   'Denmark',
   :   'Ethiopia',
   :   'Finland',
   :   'Germany'
   : ] [ 'Hungary', 'Ireland', 'Japan', 'Kenya' ]
