#+title: Exercise 02

** Exercise
*** Level 2

1) Quadratic equation is calculated as follows: ax2 + bx + c = 0. Write a function which calculates value or values of a quadratic equation, solveQuadEquation.

   #+NAME: quadratic-equation
   #+begin_src js
console.log(solveQuadratic()) // {0}
console.log(solveQuadratic(1, 4, 4)) // {-2}
console.log(solveQuadratic(1, -1, -2)) // {2, -1}
console.log(solveQuadratic(1, 7, 12)) // {-3, -4}
console.log(solveQuadratic(1, 0, -4)) //{2, -2}
console.log(solveQuadratic(1, -1, 0)) //{1, 0}
   #+end_src

   #+begin_src js :results output :noweb yes
function solveQuadEquation(a, b, c) {
    let solvedEquation1 = ((-b + ((b * b) - 4 * a * c)) / 2 * a)
    let solvedEquation2 = ((-b - ((b * b) - 4 * a * c)) / 2 * a)

    let answers = Array()
    if (solvedEquation1 === solvedEquation2) {
        answers.push(solvedEquation1)
    }
    else {
        answers.push(solvedEquation1, solvedEquation2)
    }

    return answers;
}

console.log(solveQuadEquation()) // {0}
console.log(solveQuadEquation(1, 4, 4)) // {-2}
console.log(solveQuadEquation(1, -1, -2)) // {2, -1}
console.log(solveQuadEquation(1, 7, 12)) // {-3, -4}
console.log(solveQuadEquation(1, 0, -4)) //{2, -2}
console.log(solveQuadEquation(1, -1, 0)) //{1, 0}
   #+end_src

   #+RESULTS:
   : [ NaN, NaN ]
   : [ -2 ]
   : [ 5, -4 ]
   : [ -3, -4 ]
   : [ 8, -8 ]
   : [ 1, 0 ]

2) Declare a function named /printArray/. It takes array as a parameter, and it prints each value of the array.

   #+begin_src js :results output
function printArray(arr) {
    arr.forEach((i) => console.log(i))
}

printArray(['Apple', 'Banana', 'Orange'])
   #+end_src

   #+RESULTS:
   : Apple
   : Banana
   : Orange

3) Write a function name /showDateTime/ which shows time in this format: 08/01/2020 04:08 using the date object.

   #+begin_src js :results output
function showDateTime() {
    let date = new Date();

    let getYear = date.getFullYear();
    let getMonth = date.getMonth() < 10 ? '0' + date.getMonth() : date.getMonth();
    let getToday = date.getDate() < 10 ? '0' + date.getDate() : date.getDate();
    let getHour = date.getHours() < 10 ? '0' + date.getHours() : date.getHours();
    let getMinutes = date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes();

    console.log(`${getMonth}/${getToday}/${getYear} ${getHour}:${getMinutes}`)
}

showDateTime()
   #+end_src

   #+RESULTS:
   : 08/03/2026 12:13

4) Declare a function name /swapValues/. This function swaps value of x to y.

   #+begin_src js
swapValues(3, 4) // x => 4, y=>3
swapValues(4, 5) // x = 5, y = 4
   #+end_src

   #+begin_src js :results output
function swapValues(x, y) {
    let a = x;
    let b = y;

    x = b;
    y = a;

    console.log(x, y)
}

swapValues(3, 4)
swapValues(4, 5)
   #+end_src

   #+RESULTS:
   : 4 3
   : 5 4

5) Declare a function name /reverseArray/. It takes array as an parameter and it turns the reverse of the array (don't use the method).

   #+begin_src js :results output
function reverseArray(arr) {
    let reversedArray = Array();
    arr.forEach((i) => reversedArray.unshift(i))
    return reversedArray;
}

console.log(reverseArray([1, 2, 3, 4, 5]))
console.log(reverseArray(['A','B', 'C']))
   #+end_src

   #+RESULTS:
   : [ 5, 4, 3, 2, 1 ]
   : [ 'C', 'B', 'A' ]

6) Declare a function name /capitalizeArray/. It takes a parameter and it turns the - capitalizedArray

   #+begin_src js :results output
function capitalizeArray(arr) {
    let returnArray = Array()
    arr.forEach((i) => { returnArray.push(i.toUpperCase()) })
    return returnArray;
}

console.log(capitalizeArray(['a', 'b', 'c']))
   #+end_src

   #+RESULTS:
   : [ 'A', 'B', 'C' ]

7) Declare a function name /addItem/. It takes an item parameter and it returns an array after adding an item.

   #+begin_src js :results output
function addItem(arr, item) {
   arr.push(item);
    return arr[arr.length - 1];
}

console.log(addItem(['Milk', 'Banana', 'Apple'], 'Bread'))
   #+end_src

   #+RESULTS:
   : Bread
